services:

  database:
    image: postgres:latest
    container_name: blog_db
    restart: always
    env_file: env/.env.prod
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: server/docker/Dockerfile.prod
    env_file: env/.env.prod
    depends_on:
      database:
        condition: service_healthy
    restart: no
    ports:
      - 5174:5174
    container_name: blog_server

  client:
    build:
      context: .
      dockerfile: client/config/Dockerfile.prod
    depends_on:
      - server
    restart: no
    ports:
      - 5173:80
    container_name: blog_client

volumes:
  pg_data: