services:

  database:
    image: postgres:latest
    container_name: blog_db
    restart: no
    # This file needs to be referred to twice:
    # 1. here to set env vars in the **container**,
    # 2. in the command line (--env-file) to set env vars in this config.
    env_file: database/.env.dev
    ports:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  server:
    image: blog_server
    container_name: blog_server
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: server
    env_file:
      - database/.env.dev
      - packages/server/.env.dev
    depends_on:
      database:
        condition: service_healthy
    restart: no
    ports:
      - 5174:5174
    volumes:
      - .:/app

  client:
    image: blog_client
    container_name: blog_client
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: client
    depends_on:
      - server
    restart: no
    ports:
      - 5173:5173
    volumes:
      - .:/app

volumes:
  pg_data: