services:

  database:
    image: postgres:latest
    container_name: blog_db
    restart: no
    # This file needs to be referred to twice:
    # 1. here to set env vars in the **container**,
    # 2. in the command line (--env-file) to set env vars in this config.
    env_file: env/.env.dev
    ports:
      - 5175:5432
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: docker/Dockerfile.dev
    env_file: env/.env.dev
    depends_on:
      database:
        condition: service_healthy
    restart: no
    ports:
      - 5174:5174
    container_name: blog_server
    volumes:
      - ./server:/app

  client:
    build:
      context: ./client
      dockerfile: config/Dockerfile.dev
    depends_on:
      - server
    restart: no
    ports:
      - 5173:5173
    container_name: blog_client
    volumes:
      - ./client:/app

volumes:
  pg_data: