services:

  database:
    container_name: blog_db
    image: postgres:latest
    restart: always
    env_file: database/.env.prod
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    container_name: blog_server
    build:
      context: .
      dockerfile: server/config/Dockerfile.prod
    env_file:
      - database/.env.dev
      - server/config/.env.dev
    depends_on:
      database:
        condition: service_healthy
    restart: no
    ports:
      - 5174:5174

  client:
    container_name: blog_client
    build:
      context: .
      dockerfile: client/config/Dockerfile.prod
    depends_on:
      - server
    restart: no
    ports:
      - 5173:80

volumes:
  pg_data: